pontoon/administration/urls.py
from django.conf.urls.defaults import *

import views

urlpatterns = patterns(
    '',

    # Admin Home
    url(r'^$', views.admin,
        name='pontoon.admin'),

    # Add new project
    url(r'^projects/$', views.manage_project,
        name='pontoon.admin.project.new'),

    # Edit project
    url(r'^projects/(?P<slug>.+)/$', views.manage_project,
        name='pontoon.admin.project'),

    # Delete project
    url(r'^delete/(?P<pk>\d+)/$', views.delete_project,
        name='pontoon.admin.project.delete'),

    # Update from repository
    url(r'^repository/$', views.update_from_repository,
        name='pontoon.admin.repository.update'),

    # Update from Transifex
    url(r'^transifex/$', views.update_from_transifex,
        name='pontoon.admin.transifex.update'),

    # Get slug
    url(r'^get-slug/$', views.get_slug,
        name='pontoon.admin.get_slug'),
)

pontoon/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from django.views.generic import TemplateView

from funfactory.monkeypatches import patch
patch()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',

    # Legacy: Locale redirect for compatibility with i18n ready URL scheme
    (r'^en-US(?P<url>.+)$', RedirectView.as_view(url="%(url)s")),

    # Admin
    (r'admin/', include('pontoon.administration.urls')),

    # Django admin
    (r'^a/', include(admin.site.urls)),

    # Test project: Pontoon Intro
    url(r'^intro/$', 'pontoon.intro.views.intro'),

    # BrowserID
    url(r'^browserid/$', 'pontoon.base.views.verify', name='browserid.verify'),

    # Logout
    url(r'^signout/$', 'django.contrib.auth.views.logout', {'next_page': '/'},
        name='signout'),

    # Error pages
    url(r'^403/$', TemplateView.as_view(template_name='403.html')),
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),

    # Favicon
    url(r'^favicon\.ico$',
        RedirectView.as_view(url='/static/img/favicon.ico')),

    # Include script
    url(r'^pontoon\.js$',
        RedirectView.as_view(url='/static/js/pontoon.js')),

    # Main app: Must be at the end
    (r'', include('pontoon.base.urls')),
)

# In DEBUG mode, serve media files through Django.
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

pontoon/administration/models.py
from django.db import models

# Create your models here.

pontoon/base/models.py
import commonware.log
import datetime
import json

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_save
from django.forms import ModelForm


log = commonware.log.getLogger('pontoon')


class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    transifex_username = models.CharField(max_length=40, blank=True)
    transifex_password = models.CharField(max_length=128, blank=True)
    svn_username = models.CharField(max_length=40, blank=True)
    svn_password = models.CharField(max_length=128, blank=True)
    quality_checks = models.BooleanField(default=True)


class Locale(models.Model):
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=128)
    nplurals = models.SmallIntegerField(null=True, blank=True)
    plural_rule = models.CharField(max_length=128, blank=True)

    def __unicode__(self):
        return self.name

    def stringify(self):
        return json.dumps({
            'code': self.code,
            'name': self.name,
            'nplurals': self.nplurals,
            'plural_rule': self.plural_rule,
        })


class Project(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True)
    locales = models.ManyToManyField(Locale)

    # Repositories
    REPOSITORY_TYPE_CHOICES = (
        ('file', 'File'),
        ('git', 'Git'),
        ('hg', 'HG'),
        ('svn', 'SVN'),
        ('transifex', 'Transifex'),
    )

    repository_type = models.CharField(
        "Type", max_length=20, blank=False, default='File',
        choices=REPOSITORY_TYPE_CHOICES)

    # URLField does not take git@github.com:user/project.git URLs
    repository_url = models.CharField("URL", max_length=2000, blank=True)

    # Includes source directory in one-locale repositories
    repository_path = models.TextField(blank=True)

    transifex_project = models.CharField(
        "Project", max_length=128, blank=True)
    transifex_resource = models.CharField(
        "Resource", max_length=128, blank=True)

    # Project info
    info_brief = models.TextField("Project info", blank=True)

    # Website for in place localization
    url = models.URLField("URL", blank=True)
    width = models.PositiveIntegerField(
        "Default website (iframe) width in pixels. If set, \
        sidebar will be opened by default.", null=True, blank=True)
    links = models.BooleanField(
        "Keep links on the project website clickable")

    class Meta:
        permissions = (
            ("can_manage", "Can manage projects"),
            ("can_localize", "Can localize projects"),
        )

    def __unicode__(self):
        return self.name


class Subpage(models.Model):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=128)
    url = models.URLField("URL", blank=True)  # Firefox OS Hack

    def __unicode__(self):
        return self.name


class Resource(models.Model):
    project = models.ForeignKey(Project)
    path = models.TextField()  # Path to localization file
    entity_count = models.PositiveIntegerField(default=0)

    # Format
    FORMAT_CHOICES = (
        ('po', 'po'),
        ('properties', 'properties'),
        ('dtd', 'dtd'),
        ('ini', 'ini'),
        ('lang', 'lang'),
    )
    format = models.CharField(
        "Format", max_length=20, blank=True, choices=FORMAT_CHOICES)

    def __unicode__(self):
        return '%s: %s' % (self.project.name, self.path)


class Entity(models.Model):
    resource = models.ForeignKey(Resource)
    string = models.TextField()
    string_plural = models.TextField(blank=True)
    key = models.TextField(blank=True)  # Needed for webL10n
    comment = models.TextField(blank=True)
    order = models.PositiveIntegerField(default=0)
    source = models.TextField(blank=True)  # Path to source code file
    obsolete = models.BooleanField(default=False)

    def __unicode__(self):
        return self.string

    def serialize(self):
        try:
            source = eval(self.source)
        except SyntaxError:
            source = self.source

        return {
            'pk': self.pk,
            'original': self.string,
            'original_plural': self.string_plural,
            'key': self.key,
            'path': self.resource.path,
            'format': self.resource.format,
            'comment': self.comment,
            'order': self.order,
            'source': source,
            'obsolete': self.obsolete,
        }


class Translation(models.Model):
    entity = models.ForeignKey(Entity)
    locale = models.ForeignKey(Locale)
    user = models.ForeignKey(User, null=True, blank=True)
    string = models.TextField()
    # 0=zero, 1=one, 2=two, 3=few, 4=many, 5=other, null=no plural forms
    plural_form = models.SmallIntegerField(null=True, blank=True)
    date = models.DateTimeField()
    approved = models.BooleanField(default=False)
    fuzzy = models.BooleanField(default=False)

    def __unicode__(self):
        return self.string

    def save(self, stats=True, *args, **kwargs):
        super(Translation, self).save(*args, **kwargs)
        if stats:
            update_stats(self.entity.resource, self.locale)

    def delete(self, stats=True, *args, **kwargs):
        super(Translation, self).delete(*args, **kwargs)
        if stats:
            update_stats(self.entity.resource, self.locale)

    def serialize(self):
        return {
            'pk': self.pk,
            'string': self.string,
            'approved': self.approved,
            'fuzzy': self.fuzzy,
        }


class Stats(models.Model):
    resource = models.ForeignKey(Resource)
    locale = models.ForeignKey(Locale)
    translated_count = models.PositiveIntegerField(default=0)
    approved_count = models.PositiveIntegerField(default=0)
    fuzzy_count = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        translated = float(self.translated_count + self.approved_count)
        percent = 0
        if self.resource.entity_count > 0:
            percent = translated * 100 / self.resource.entity_count
        return str(int(round(percent)))


class ProjectForm(ModelForm):
    class Meta:
        model = Project

    def clean(self):
        cleaned_data = super(ProjectForm, self).clean()
        repository_url = cleaned_data.get("repository_url")
        repository_type = cleaned_data.get("repository_type")
        transifex_project = cleaned_data.get("transifex_project")
        transifex_resource = cleaned_data.get("transifex_resource")

        if repository_type == 'Transifex':
            if not transifex_project:
                self._errors["repository_url"] = self.error_class(
                    [u"You need to provide Transifex project and resource."])
                del cleaned_data["transifex_resource"]

            if not transifex_resource:
                self._errors["repository_url"] = self.error_class(
                    [u"You need to provide Transifex project and resource."])
                del cleaned_data["transifex_project"]

        elif not repository_url:
            self._errors["repository_url"] = self.error_class(
                [u"You need to provide a valid URL."])

        return cleaned_data


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

# For every newly created user
post_save.connect(create_user_profile, sender=User)


def get_entities(project, locale, path=None):
    """Load project entities with locale translations."""

    resources = Resource.objects.filter(project=project)
    if path:
        resources = resources.filter(path=path)

    entities = Entity.objects.filter(resource__in=resources, obsolete=False)
    entities_array = []

    for e in entities:
        translation_array = []

        # Entities without plurals
        if e.string_plural == "":
            translation = get_translation(entity=e, locale=locale)
            translation_array.append(translation.serialize())

        # Pluralized entities
        else:
            for i in range(0, locale.nplurals or 1):
                translation = get_translation(
                    entity=e, locale=locale, plural_form=i)
                translation_array.append(translation.serialize())

        obj = e.serialize()
        obj["translation"] = translation_array

        entities_array.append(obj)
    return sorted(entities_array, key=lambda k: k['order'])


def get_chart_data(stats):
    """Get chart data for stats."""

    return stats.aggregate(
        total=Sum('resource__entity_count'),
        approved=Sum('approved_count'),
        translated=Sum('translated_count'),
        fuzzy=Sum('fuzzy_count')
    )


def get_locales_stats(locales, project):
    """Add chart data to locales for specified project."""

    for locale in locales:
        r = Entity.objects.filter(obsolete=False).values('resource')
        resources = Resource.objects.filter(project=project, pk__in=r)
        stats = Stats.objects.filter(resource__in=resources, locale=locale)

        locale.chart = get_chart_data(stats)

    return locales


def get_projects_stats(projects, locale=None):
    """Add chart data to projects (for specified locale)."""

    for project in projects:
        r = Entity.objects.filter(obsolete=False).values('resource')
        resources = Resource.objects.filter(project=project, pk__in=r)
        stats = Stats.objects.filter(resource__in=resources)

        if locale:
            stats = stats.filter(locale=locale)

        project.chart = get_chart_data(stats)

    return projects


def get_translation(entity, locale, plural_form=None, fuzzy=None):
    """Get translation of a given entity to a given locale in a given form."""

    translations = Translation.objects.filter(

pontoon/administration/templates/admin.html
{% extends "landing.html" %}

{% block title %}Pontoon &middot; Admin{% endblock %}

{% block class %}admin{% endblock %}

{% block heading %}Admin{% endblock %}

{% block subtitle %}Don't mess it up. Please.{% endblock %}

{% block middle %}
<form>
  <div class="add">
    <a href="{{ url('pontoon.admin.project.new') }}">Add new project</a>
  </div>

  {% include 'project_selector.html' %}
</form>
{% endblock %}

{% block extend_css %}
  <link rel="stylesheet" href="{{ static('css/admin.css') }}">
{% endblock %}

{% block extend_js %}
  {% compress js %}
  <script src="{{ static('js/admin.js') }}"></script>
  {% endcompress %}
{% endblock %}

pontoon/administration/templates/admin_project.html
{% extends "base.html" %}

{% block title %}Pontoon &middot; {{'%(subtitle)s' | format(subtitle=subtitle) }}{% endblock %}

{% block class %}admin-project{% endblock %}

{% block content %}
<nav>
  <ul class="links">
    <li><a href="{{ url('pontoon.home') }}" title="Home">Home</a></li>
    <li><a href="{{ url('pontoon.admin') }}" title="Admin">Admin</a></li>
    {% if pk %}
    <li><a href="{{ url('pontoon.admin.project.new') }}" title="Add new project">Add</a></li>
      {% if translate_locale and form.slug.value() != '' %}
      <li class="translate{% if not ready %} hidden{% endif %}"><a href="{{ url('pontoon.translate', translate_locale, form.slug.value()) }}" title="Translate project">Translate</a></li>
      {% endif %}
    {% endif %}
  </ul>
</nav>

<form method="POST" action="{{ request.path }}" class="{% if pk %}edit{% else %}add{% endif %}">

  <h1 id="title">{{ '%(subtitle)s' | format(subtitle=subtitle) }}</h1>
  <ul class="notification{% if not messages %} hidden{% endif %}">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
  {% if pk %}
  <input type="hidden" value="{{ pk }}" name="pk">
  {{ form.repository_path.as_hidden() }}
  {% endif %}

  <div class="clearfix">
      {{ form.name.label_tag() }}
      {{ form.name }}
      {{ form.name.errors }}
  </div>
  <div class="clearfix">
      {{ form.slug.label_tag() }}
      {{ form.slug }}
      {{ form.slug.errors }}
  </div>
  <div class="locales clearfix">
      <div class="locale select">
        <label for="available">Available locales<a class="choose-all" href="#choose-all">Choose all &rarr;</a></label>
        <div class="menu">
          <div class="search-wrapper clearfix">
            <div class="icon fa fa-search"></div>
            <input id="available" type="search" autocomplete="off">
          </div>
          <ul>
            {% for locale in locales_available %}
            <li data-id="{{ locale.id }}"><span class="language {{ locale.code }}">{{ locale.name }}</span><span class="code">{{ locale.code }}</span></li>
            {% endfor %}
            <li class="no-match">No results</li>
          </ul>
        </div>
      </div>
      <div class="locale select selected">
        <label for="selected">Chosen locales<a class="remove-all" href="#remove-all">&larr; Remove all</a></label>
        <div class="menu">
          <div class="search-wrapper clearfix">
            <div class="icon fa fa-search"></div>
            <input id="selected" type="search" autocomplete="off">
          </div>
          <ul>
            {% for locale in locales_selected %}
            <li data-id="{{ locale.id }}"><span class="language {{ locale.code }}">{{ locale.name }}</span><span class="code">{{ locale.code }}</span></li>
            {% endfor %}
            <li class="no-match">No results</li>
          </ul>
        </div>
      </div>
      {{ form.locales }}
      {{ form.locales.errors }}
  </div>

  <h2>Repository</h2>

  <div class="repository clearfix">
      <section class="type-wrapper">
          {{ form.repository_type.label_tag() }}
          <div class="type select">
            <div class="hidden">
              {{ form.repository_type }}
            </div>
            <div class="button selector">
              <span class="title"></span>
              <span> &#9652;</span>
            </div>
            <ul class="menu">
              {% for choice in REPOSITORY_TYPE_CHOICES %}
                  <li data-type="{{ choice[0] }}">{{ choice[1] }}</li>
              {% endfor %}
            </ul>
          </div>
          <p class="authentication-title">Please sign in</p>
      </section>
      <section class="details-wrapper" data-repository-type="{{ form.repository_type.value()|lower }}">
          <div class="repo">
              {{ form.repository_url.label_tag() }}
              {{ form.repository_url }}
              {% if pk %}
              <button title="Update all locales from repository" data-source="repository" class="button update">
                  <span class="fa fa-refresh"></span>
              </button>
              {% endif %}
          </div>
          <div class="transifex clearfix">
              {{ form.transifex_project.label_tag() }}
              {{ form.transifex_resource.label_tag() }}
              {{ form.transifex_project }}
              {{ form.transifex_resource }}
              {% if pk %}
              <button title="Update all locales from Transifex" data-source="transifex" class="button update">
                  <span class="fa fa-refresh"></span>
              </button>
              <section class="authentication-form">
                  <label for="id_transifex_username">Username or email</label>
                  <label for="id_transifex_password">Password</label>
                  <input id="id_transifex_username" name="transifex_username" type="text" />
                  <input id="id_transifex_password" name="transifex_password" type="password" />
              </section>
              <div class="bottom">
                  <label class="remember">
                      <input name="remember" type="checkbox" />Remember me
                  </label>
                  <a class="new" target="_blank" href="http://www.transifex.com/signup/">New to Transifex?</a>
              </div>
              {% endif %}
          </div>
      </section>
      {{ form.repository_url.errors }}
      {{ form.transifex_project.errors }}
      {{ form.transifex_resource.errors }}
  </div>

  <h2>Website</h2>

  <div class="clearfix">
      {{ form.url.label_tag() }}
      {{ form.url }}
      {{ form.url.errors }}
  </div>
  <div class="clearfix">
      {{ form.width.label_tag() }}
      {{ form.width }}
      {{ form.width.errors }}
  </div>
  <div class="checkbox clearfix">
      <label for="id_links">
          {{ form.links }}{{ form.links.label }}
      </label>
  </div>

  <h2>Subpages
      <span class="small">(optional)</span>
      <a href="#add-subpage" class="add-subpage">Add more</a>
  </h2>

  {{ formset.management_form }}
  {% for form in formset %}
      {{ form.id }}
  <div class="subpages clearfix">
      {{ form.name.label_tag() }}
      {{ form.url.label_tag() }}
      {{ form.name }}
      {{ form.url }}
      <button title="Delete subpage" class="button delete-subpage fa fa-trash-o" tabindex="-1"></button>
      {{ form.DELETE }}
      {{ form.name.errors }}
      {{ form.url.errors }}
  </div>
  {% endfor %}
  <div class="subpages clearfix" data-count="{{ formset.total_form_count() }}">
      {{ formset.empty_form.name.label_tag() }}
      {{ formset.empty_form.url.label_tag() }}
      {{ formset.empty_form.name }}
      {{ formset.empty_form.url }}
      <button title="Delete subpage" class="button delete-subpage fa fa-trash-o" tabindex="-1"></button>
      {{ formset.empty_form.DELETE }}
      {{ formset.empty_form.name.errors }}
      {{ formset.empty_form.url.errors }}
  </div>

  <h2>Project info <span class="small">(optional)</span></h2>

  <div>
      {{ form.info_brief }}
      <p class="subtitle">Supports HTML</p>
      {{ form.info_brief.errors }}
  </div>

  <div class="controls clearfix">
      {% if pk %}<button class="button delete-project">Delete project</button>{% endif %}
      <button class="button">Save project</button>
      <a href="{{ url('pontoon.admin') }}" class="cancel">Cancel</a>
  </div>

</form>
{% endblock %}

{% block extend_css %}
  <link rel="stylesheet" href="{{ static('css/admin_project.css') }}">
{% endblock %}

{% block extend_js %}
  {% compress js %}
  <script src="{{ static('js/admin_project.js') }}"></script>
  {% endcompress %}
{% endblock %}